import { NULL_ID } from '../constants'

export const GET_POLL_INFO_ENCODED_RESPONSE_MOCK =
	'AQAAAAAAAABUaGlyZF9tYWlubmV0X3BvbGwAAAAAAAAAAAAAAAAAAAIAAAAAAAAA6AMAAAAAAAABAAAAAAAAAKoC/67Bv5MXJHV7XKoiLw1xiiqUMNSC+pDQ+RH8nPnjcqLQgPqKZHgjlhalCDfsEpxFMkr/q9O7HxKgkB46Se5HQVJUSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAaHR0cHM6Ly9naXRodWIuY29tL3F1YmljL3Rlc3QtMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=='

export const GET_POLL_INFO_DECODED_RESPONSE_MOCK = {
	found: 1,
	poll_info: {
		poll_name: 'Third_mainnet_poll',
		poll_type: 2,
		min_amount: 1000,
		is_active: 1,
		creator: 'IPRVRRNTUTWURASNKZTIZDYSVYJAHFKIGRLRLIDEHHIUCTAAJLFASDQGAXWN',
		allowed_assets: [
			{
				issuer: 'GARTHFANXMPXMDPEZFQPWFPYMHOAWTKILINCTRMVLFFVATKVJRKEDYXGHJBF',
				assetName: 'GARTH'
			},
			{
				issuer: NULL_ID,
				assetName: 'N/A'
			},
			{
				issuer: NULL_ID,
				assetName: 'N/A'
			},
			{
				issuer: NULL_ID,
				assetName: 'N/A'
			},
			{
				issuer: NULL_ID,
				assetName: 'N/A'
			},
			{
				issuer: NULL_ID,
				assetName: 'N/A'
			},
			{
				issuer: NULL_ID,
				assetName: 'N/A'
			},
			{
				issuer: NULL_ID,
				assetName: 'N/A'
			},
			{
				issuer: NULL_ID,
				assetName: 'N/A'
			},
			{
				issuer: NULL_ID,
				assetName: 'N/A'
			},
			{
				issuer: NULL_ID,
				assetName: 'N/A'
			},
			{
				issuer: NULL_ID,
				assetName: 'N/A'
			},
			{
				issuer: NULL_ID,
				assetName: 'N/A'
			},
			{
				issuer: NULL_ID,
				assetName: 'N/A'
			},
			{
				issuer: NULL_ID,
				assetName: 'N/A'
			},
			{
				issuer: NULL_ID,
				assetName: 'N/A'
			}
		],
		num_assets: 1
	},
	poll_link: 'https://github.com/qubic/test-3'
}
